name = "ws-on-worker"
main = "build/worker/shim.mjs"
compatibility_date = "2024-05-09"


[build]
command = "cargo install -q worker-build && (test $OHKAMI_WORKER_DEV && (echo 'dev' && worker-build --dev) || worker-build)"

[durable_objects]
bindings = [
    { name = "ROOMS", class_name = "Room" }
]

[[migrations]]
tag = "v1"
new_classes = ["Room"]
